### PR TITLE
Feature/rest api tutorials

### PR DESCRIPTION
**Pull request by jyecusch**
Just waiting on a patch release of the Node SDK and updated Python SDK Template for this to be ready.

### CODE REVIEW

**Comment by davemooreuws** [comment]
Maybe these should go under guides? With a new sidebar menu and new item in nav

**Comment by jyecusch** [comment]
Closes: https://github.com/nitrictech/docs/issues/45

**Review by davemooreuws — DISMISSED** [review]
Looks good, please review my PR into this for guides. Then we can merge once website is ready.

**Review by davemooreuws — APPROVED** [review]
@jyecusch I believe this can be merged in. The link will go live. But no navigation and sidebar until staging site is merged. (this is ok)

**Pull request merged**
